# Generated by Django 3.2.9 on 2021-11-30 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photos.editor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_imagen',
            field=models.ImageField(default=1, upload_to='articles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
