# Generated by Django 3.2.9 on 2021-11-30 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='Caption',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
