# Generated by Django 3.2.9 on 2021-11-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20211130_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='photo_imagen',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_imagen',
            new_name='article_image',
        ),
    ]
