# Generated by Django 3.2.9 on 2021-11-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
